### ISSUE TITLE
InterruptIn error: irq channel conflict when BLE.begin() is called.

### ISSUE THREAD

**Issue by chminh-ph** [arduino-libraries/Arduino_MachineControl#102]
Hello,
I'm working with Portenta H7 using ArduinoBLE and Arduino_MachineControl libraries. The code is working well individually, but as I combine them the issue will be occurred. When BLE.begin() is called in setup() function, the red LED on board starts blinking right after that. I got the MbedOS printed messages here:

```
++ MbedOS Error Info ++
Error Status: 0x80FF0100 Code: 256 Module: 255
Error Message: Fatal Run-time error
Location: 0x807728F
Error Value: 0x0
Current Thread: main Id: 0x240054F8 Entry: 0x804D959 StackSize: 0x8000 StackMem: 0x24005540 SP: 0x2400D37C 
For more info, visit: https://mbed.com/s/error?error=0x80FF0100&osver=61600&core=0x411FC271&comp=2&ver=120200&tgt=PORTENTA_H7_M7
-- MbedOS Error Info --
InterruptIn error: irq channel conflict
```

**Comment by per1234** [comment]
Hi @chminh-ph. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/Arduino_MachineControl/issues/73.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
