### ISSUE TITLE
PT1000 isn´t compatible

### ISSUE THREAD

**Issue by AceTecNic** [arduino-libraries/Arduino_MachineControl#104]
In the "**Temp_probes_RTD**" example sketch, you describe that a PT1000 is also possible:

https://github.com/arduino-libraries/Arduino_MachineControl/blob/7e5974e76efc3f4c63aac2d9255b5eea8108dcb1/examples/Temp_probes_RTD/Temp_probes_RTD.ino#L21-L24

Now your support writes me that this is not possible. Please take that out of the comment in the code, just causes confusion. Thanks :)

**Comment by MDBInd** [comment]
Like you, I was advised on 08/02/23 that "Unfortunately at the moment PT1000 are not supported" by Arduino support. It is quite confusing as PT1000 is printed on the board. Hopefully it will be supported in the future.

**Comment by MDBInd** [comment]
Quick update, in the latest version of the [documentation](https://docs.arduino.cc/resources/datasheets/AKX00032-datasheet.pdf) (Updated 08/05//2023) all references of PT1000 have been removed.

**Comment by leonardocavagnis** [comment]
Hi @AceTecNic, @MDBInd 
I confirm that it is not compatible. All references to pt1000 have been removed.
