### ISSUE TITLE
Mode for analog in channels should be set individually

### ISSUE THREAD

**Issue by jonas-hagen** [arduino-libraries/Arduino_MachineControl#109]
The analog in channels support three modes:

- 0 - 10 V
- 0 - 20 mA
- NTC (resistance)

The modes are set in functions like this, for all three channels:
https://github.com/arduino-libraries/Arduino_MachineControl/blob/a9845d2ca3ef3ed8ef0a90e63e1d60536d8017a2/src/Arduino_MachineControl.h#L265

Hardware supports to configure the channels individually, as all `ANALOG_IN_CH_SEL` lines are connected to individual MCU pins.

An API like this would be great (for all three modes, here shown with NTC mode):
```
analog_in.set0_10V(); // sets all analog in channels (existing)
analog_in.setNTC(2); // sets mode for channel 2 (new)

raw_adc = analog_in.read(2); // esisting
```

---

Related: https://github.com/arduino-libraries/Arduino_MachineControl/pull/101

**Comment by leonardocavagnis** [comment]
Hi @jonas-hagen,
Thank you for proposing this change. We've decided not to implement it.
The reason for this decision is our concern for hardware safety. Incorrect management could potentially damage the board.
