### ISSUE TITLE
RS-485 full duplex example disables the receiver when sending data

### ISSUE THREAD

**Issue by marcocipriani01** [arduino-libraries/Arduino_MachineControl#110]
Hello,
At the moment, the [RS-485 full duplex example](https://github.com/arduino-libraries/Arduino_MachineControl/blob/master/examples/RS485_fullduplex/RS485_fullduplex.ino) disables the receiver when sending data. This defeats the purpose of full duplex:

```cpp
comm_protocols.rs485.noReceive();

comm_protocols.rs485.beginTransmission();

comm_protocols.rs485.print("hello ");
comm_protocols.rs485.println(counter++);

comm_protocols.rs485.endTransmission();
        
// Re-enable receive mode after transmission
comm_protocols.rs485.receive();
```

If this is not necessary, the example should be changed to leaving the receiver enabled.

If this is necessary (perhaps due to a physical limitation of the Portenta Machine Control that requires the receiver to be disabled when sending data???) then the limitation should be clearly documented.

**Comment by manchoz** [comment]
Hi @marcocipriani01,
Yes, it is necessary and depends on the fact that the [RS485 transceiver](https://www.maxlinear.com/product/interface/serial-transceivers/multiprotocol/dual-protocol/sp335) in use still has a half-duplex UART (with flow control) facing the microcontroller (please see pag. 7 of [Portenta Machine Control Schematics](https://docs.arduino.cc/resources/schematics/AKX00032-schematics.pdf)).

So, while you are transmitting and receiving on two separate pairs of lines on the fieldbus side, you need to deal with having just a single UART (TX/RX + RTS/CTS) for both transmitting and receiving on the Arduino side.

The behavior you see in the sketch is to accommodate this architecture.

**Comment by marcocipriani01** [comment]
Hi @manchoz,
Sorry, something doesn't add up with the documents you linked:

- The SP335E transceiver seems to be perfectly capable of full-duplex RS-422 communication. It's written on the first page of the datasheet (_1 Driver, 1 Receiver RS-485/422, Full or Half Duplex Configuration_), in the pin description table, plus two separate TX and RX pins are shown in this diagram:

![image](https://github.com/arduino-libraries/Arduino_MachineControl/assets/20319029/4e1ae91e-736f-4e6f-8a98-70b15329a537)

- On page 7 of the schematic, there are four separate pins for TX, RX, CTS and RTS (CTS and RTS are not used in RS-422 mode according to the SP335E datasheet):

![image](https://github.com/arduino-libraries/Arduino_MachineControl/assets/20319029/51e61624-0779-4cfb-9081-cb06cb11df34)

- Those pins are connected to the UART4 interface:

![image](https://github.com/arduino-libraries/Arduino_MachineControl/assets/20319029/0bd51974-487f-4950-ae07-f0fab9517dc7)

- Which is shown to be connected to four pins on page 4, one for each signal (thus the RX and TX pins are not the same):

![image](https://github.com/arduino-libraries/Arduino_MachineControl/assets/20319029/e28c7db2-4192-4ad9-a4a1-598002fead6a)

- While the STM32H747XI MCU does support half-duplex single-wire UART on the UART4 interface, this obviously requires that only one pin is used for both TX and RX:

![image](https://github.com/arduino-libraries/Arduino_MachineControl/assets/20319029/704db44e-b9c1-405b-beae-fabf8017296b)

Please let me know if I'm missing something,
Marco Cipriani

**Comment by marcocipriani01** [comment]
I don't have an issue with the code or the library, all I'm saying is that the full-duplex example probably doesn't need `comm_protocols.rs485.noReceive()` and `comm_protocols.rs485.receive()`. I will make some tests this week to confirm (or eventually deny) that the Portenta Machine Control can send and receive at the same time using the RS-422 port, like any other UART interface. In theory, it should behave like an Arduino UNO's UART interface, so sending data any time without stopping the reception on the RX pin. UART interfaces have buffers that operate without the need for a second core.
