### ISSUE TITLE
More USB host examples

### ISSUE THREAD

**Issue by marcocipriani01** [arduino-libraries/Arduino_MachineControl#111]
Hello,
I was wondering if you could expand the current [USB host example](https://github.com/arduino-libraries/Arduino_MachineControl/blob/master/examples/USB_host/USB_host.ino) or add more examples. In particular, I'm looking into using the USB Type-A port on the Portenta Machine Control to access a text file on a USB drive containing the configuration for my device, which is probably the most common use case for a USB port on an industrial control unit. I can't really find a lot of information online on how to do that, not even the [Portenta Breakout library](https://github.com/arduino-libraries/Arduino_PortentaBreakout/) has examples on how to use the USB Type-A port.
In the future, I would suggest adding the possibility of updating the firmware using a USB drive, however I don't need it right now.
Regards,
Marco Cipriani

**Comment by manchoz** [comment]
Hi @marcocipriani01,
please see https://github.com/arduino-libraries/Arduino_USBHostMbed5
