### ISSUE TITLE
I2Cdev is old and has major issues

### ISSUE THREAD

**Issue by JojoS62** [arduino-libraries/Arduino_MachineControl#119]
https://github.com/arduino-libraries/Arduino_MachineControl/blob/ca7ff9b35c6837733d398649fd4db86f10d5b252/src/utility/ioexpander/I2Cdev.cpp#L285-L286

Surrounding `Wire.requestFrom()` with `Wire.beginTransmission(devAddr);` / `Wire.endTransmission();` is not the correct usage of the Wire lib.

This bug has been fixed in I2Cdev already 2 Years ago in
https://github.com/jrowberg/i2cdevlib/commit/98a3b4ec838223fd5316de54203a6dc88718cd00

**Comment by leonardocavagnis** [comment]
Dear @JojoS62,
Thanks! I open the PR #120 

Consider that this library will be deprecated soon. Please, switch to the [new one](https://github.com/arduino-libraries/Arduino_PortentaMachineControl) (This issue will be fix also in the new).
