### ISSUE TITLE
PMC freeze when using ArduinoBLE with Arduino_MachineControl included.

### ISSUE THREAD

**Issue by Bylund** [arduino-libraries/Arduino_MachineControl#73]
Portenta Machine Control (PMC) crash when the `begin` function is called for the ArduinoBLE library when `Arduino_MachineControl.h` is included in the same sketch.

### To reproduce

1. Upload the Portenta BLE example without changes (https://docs.arduino.cc/tutorials/portenta-h7/por-ard-ble).
2. Verify functionality. (Optional).
3. Include header file Arduino_MachineControl.h. (#include <Arduino_MachineControl.h>)
4. Upload sketch and note that the Portenta Machine Control will freeze.

### Library versions used

- ArduinoBLE v1.2.1.
- Arduino_MachineControl v1.1.0.

#### Additional reports

- https://github.com/arduino-libraries/Arduino_MachineControl/issues/73#issuecomment-1177143490
- https://github.com/arduino-libraries/Arduino_MachineControl/issues/73#issuecomment-1751724141

**Comment by gmacario** [comment]
Hello,

Are there any updates on this subject?

**Comment by per1234** [comment]
I'll provide a minimal sketch that will produce the Mbed OS crash reported here:

```cpp
#include <Arduino_MachineControl.h>
#include <ArduinoBLE.h>
void setup() {
  BLE.begin();
}
void loop() {}
```

**Comment by chminh-ph** [comment]
Hello,
Remove EncoderClass in Arduino_MachineControl\src\Arduino_MachineControl.h and its object in Arduino_MachineControl\src\Objects.cpp. The issue will be solved. Because of I don't use the Encoder now so It can be a temp solution. I hope it is a key for someone will fix it in ther future.

**Comment by chminh-ph** [comment]
Hello,
Remove EncoderClass out of Arduino_MachineControl\src\Arduino_MachineControl.h and its object out of Arduino_MachineControl\src\Objects.cpp. The issue will be solved. Because of I don't use the Encoder now so It can be a temp solution. I hope it is a key for someone will fix it in the future.

**Comment by rickypid** [comment]
Hello,
I have the same problem. Are there any updates on this issue?
