### ISSUE TITLE
RTD reading too slow

### ISSUE THREAD

**Issue by pnndra** [arduino-libraries/Arduino_MachineControl#80]
the 150 ms delay seems unreasonable. time to select analog muxes shall be much slower

https://github.com/arduino-libraries/Arduino_MachineControl/blob/7697070ed1143df11aac1df8fa7583c1b08cd768/src/Arduino_MachineControl.h#L34

**Comment by Undermine28** [comment]
I was just running into this as well. Wondering if there is a way to speed it up?

**Comment by SJThomas29** [comment]
I had a go at changing the delay to 100ms and it caused instability in the results, with random spikes to ~500degC. Did also make the function non-blocking similar to the common example 'blink without delay' by having the function return a bool that is true when the change is finished. Can submit a pull request if needed.
