### ISSUE TITLE
Reading state of digital_output pins

### ISSUE THREAD

**Issue by toqduj** [arduino-libraries/Arduino_MachineControl#92]
As far as I can tell, there is no method like DigitalRead() to read the state of the digital output pins on the Portenta Machine Control. If it's not too much of a trouble, such functionality would be handy to directly have any of my remote processes read the state of a Machine Control unit. If not, I'll have to make intermediate variables to read out, but then there's a risk that the variable state is not exactly the digital output state, so I'd prefer reading the actual output instead. 

I'd imagine something like digital_outputs.get() or digital_outputs.read(), in line with the current digital_outputs.set() functionality of this library. 

Would that be possible?

**Comment by manchoz** [comment]
Hi @toqduj, no, it's not possible.

If you need that feature, you may want to switch to the Programmable Digital I/O.
