### ISSUE TITLE
How to use Hardware interrupts on Portenta H7 machine control

### ISSUE THREAD

**Issue by Jenifen** [arduino-libraries/Arduino_MachineControl#96]
can someone help me to use hardware input interrupt on Portenta H7 machine control ?
even i tried to use input inside timer callback but it didn't work and it crash !
Thanks

**Comment by per1234** [comment]
Hi @Jenifen. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
